### ISSUE TITLE
Crash NSSF and AMF by empty nsiInformationList

### ISSUE THREAD

**Issue by apssoft** [free5gc/nssf#2]
edit config/nssfcfg.yaml
```
index 759f2d9..5515b8e 100644
--- a/config/nssfcfg.yaml
+++ b/config/nssfcfg.yaml
@@ -34,10 +34,7 @@ configuration:
   nsiList: # List of available Network Slice Instance (NSI)
     - snssai: # S-NSSAI of this NSI
         sst: 1 # Slice/Service Type (uinteger, range: 0~255)
-      nsiInformationList: # Information list of this NSI
-        # the NRF to be used to select the NFs/services within the selected NSI, and an optonal ID
-        - nrfId: http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances
-          nsiId: 10
+      nsiInformationList: [] # Information list of this NSI
     - snssai: # S-NSSAI of this NSI
         sst: 1 # Slice/Service Type (uinteger, range: 0~255)
         sd: 000001 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
```
run command `./test.sh -o TestRegistration`

Then crash as these
```
2021-12-23T14:37:00+09:00 [INFO][AMF][NGAP][127.0.0.1:9487] Handle Uplink Nas Transport
2021-12-23T14:37:00+09:00 [INFO][AMF][NGAP][127.0.0.1:9487][AMF_UE_NGAP_ID:1] Uplink NAS Transport (RAN UE NGAP ID: 1)
2021-12-23T14:37:00+09:00 [INFO][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] Handle UL NAS Transport
2021-12-23T14:37:00+09:00 [INFO][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] Transport 5GSM Message to SMF
2021-12-23T14:37:00+09:00 [INFO][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] Select SMF [snssai: {Sst:1 Sd:010203}, dnn: internet]
2021-12-23T14:37:00+09:00 [INFO][NRF][DSCV] Handle NFDiscoveryRequest
2021-12-23T14:37:00+09:00 [INFO][NRF][GIN] | 200 |       127.0.0.1 | GET     | /nnrf-disc/v1/nf-instances?requester-nf-type=AMF&target-nf-type=NSSF |
2021-12-23T14:37:00+09:00 [INFO][NSSF][NsSelect] Handle NSSelectionGet


2021/12/23 14:37:00 [Recovery] 2021/12/23 - 14:37:00 panic recovered:
invalid argument to Intn
/usr/local/go/src/math/rand/rand.go:169 (0x56f7bb)
        (*Rand).Intn: panic("invalid argument to Intn")
/usr/local/go/src/math/rand/rand.go:337 (0x119df82)
        Intn: func Intn(n int) int { return globalRand.Intn(n) }
/home/nishi/free5gc-deb/free5gc/NFs/nssf/producer/nsselection_for_pdu_session.go:24 (0x119df6d)
        selectNsiInformation: idx := rand.Intn(len(nsiInformationList))
/home/nishi/free5gc-deb/free5gc/NFs/nssf/producer/nsselection_for_pdu_session.go:125 (0x119df6c)
        nsselectionForPduSession: nsiInformation := selectNsiInformation(nsiInformationList)
/home/nishi/free5gc-deb/free5gc/NFs/nssf/producer/network_slice_information_document.go:154 (0x119ad6c)
        NSSelectionGetProcedure: status = nsselectionForPduSession(param, response, problemDetails)
/home/nishi/free5gc-deb/free5gc/NFs/nssf/producer/network_slice_information_document.go:98 (0x119a940)
        HandleNSSelectionGet: response, problemDetails := NSSelectionGetProcedure(query)
/home/nishi/free5gc-deb/free5gc/NFs/nssf/nsselection/api_network_slice_information_document.go:27 (0x11a3fac)
        HTTPNetworkSliceInformationDocument: rsp := producer.HandleNSSelectionGet(req)
/home/nishi/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9d0d5a)
        (*Context).Next: c.handlers[c.index](c)
/home/nishi/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0x9e312f)
        RecoveryWithWriter.func1: c.Next()
/home/nishi/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9d0d5a)
        (*Context).Next: c.handlers[c.index](c)
/home/nishi/go/pkg/mod/github.com/free5gc/logger_util@v1.0.0/logger_util.go:65 (0x9e4cdd)
        ginToLogrus.func1: c.Next()
/home/nishi/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9d0d5a)
        (*Context).Next: c.handlers[c.index](c)
/home/nishi/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x9da805)
        (*Engine).handleHTTPRequest: c.Next()
/home/nishi/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x9d9f1c)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/home/nishi/go/pkg/mod/golang.org/x/net@v0.0.0-20211008194852-3b03d305991f/http2/server.go:2176 (0xf40b5a)
        (*serverConn).runHandler: handler(rw, req)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x469520)
        goexit: BYTE    $0x90   // NOP

2021-12-23T14:37:00+09:00 [INFO][NSSF][GIN] | 500 |       127.0.0.1 | GET     | /nnssf-nsselection/v1/network-slice-information?nf-id=1c3504bf-fddf-4895-a952-6d0ec8081bc8&nf-type=AMF&slice-info-request-for-pdu-session=%7B%22sNssai%22%3A%7B%22sst%22%3A1%2C%22sd%22%3A%22010203%22%7D%2C%22roamingIndication%22%3A%22NON_ROAMING%22%7D |
2021-12-23T14:37:00+09:00 [ERRO][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] Select SMF failed: NSSelection Get Error[undefined response type]
2021-12-23T14:37:00+09:00 [INFO][AMF][GMM][AMF_UE_NGAP_ID:1][SUPI:imsi-2089300007487] Send DL NAS Transport
2021-12-23T14:37:00+09:00 [INFO][AMF][NGAP][127.0.0.1:9487][AMF_UE_NGAP_ID:1] Send Downlink Nas Transport
    TestRegistration: registration_test.go:218:
                Error Trace:    registration_test.go:218
                Error:          Should be true
                Test:           TestRegistration
                Messages:       No PDUSessionResourceSetup received.
2021-12-23T14:37:00+09:00 [INFO][AMF][NGAP][127.0.0.1:9487] Handle PDU Session Resource Setup Response
2021-12-23T14:37:00+09:00 [ERRO][AMF][NGAP][127.0.0.1:9487][AMF_UE_NGAP_ID:1] SmContext[PDU Session ID:10] not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf1df8b]

goroutine 127 [running]:
github.com/free5gc/amf/context.(*SmContext).SmfUri(0x0, 0x0, 0x0)
        /home/nishi/free5gc-deb/free5gc/NFs/amf/context/sm_context.go:148 +0x3b
github.com/free5gc/amf/consumer.SendUpdateSmContextRequest(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/nishi/free5gc-deb/free5gc/NFs/amf/consumer/sm_context.go:405 +0x108
github.com/free5gc/amf/consumer.SendUpdateSmContextN2Info(0xc00014cb00, 0x0, 0x17627c1, 0x11, 0xc00071c9e0, 0xd, 0x10, 0x1750166, 0x5555555555555555, 0x0, ...)
        /home/nishi/free5gc-deb/free5gc/NFs/amf/consumer/sm_context.go:259 +0x140
github.com/free5gc/amf/ngap.HandlePDUSessionResourceSetupResponse(0xc0005b1400, 0xc000721880)
        /home/nishi/free5gc-deb/free5gc/NFs/amf/ngap/handler.go:1080 +0x89e
github.com/free5gc/amf/ngap.Dispatch(0x1c25140, 0xc0005416e0, 0xc000a9e000, 0x28, 0x2000)
        /home/nishi/free5gc-deb/free5gc/NFs/amf/ngap/dispatcher.go:115 +0x7e3
github.com/free5gc/amf/ngap/service.handleConnection(0xc0005416e0, 0x2000, 0x17bd470, 0x17bd478)
        /home/nishi/free5gc-deb/free5gc/NFs/amf/ngap/service/service.go:204 +0x700
created by github.com/free5gc/amf/ngap/service.listenAndServe
        /home/nishi/free5gc-deb/free5gc/NFs/amf/ngap/service/service.go:136 +0xc43
exit status 2
FAIL    test    2.002s
2021-12-23T14:37:03+09:00 [INFO][UPF][Util] Removing DNN routes
20 packets captured
20 packets received by filter
0 packets dropped by kernel
1242 packets captured
2484 packets received by filter
0 packets dropped by kernel
```

**Comment by free5gc-org** [comment]
Thanks for the PR!
